# Generated by Django 2.2.6 on 2019-10-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_art', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=100)),
                ('artiste', models.CharField(max_length=100)),
            ],
        ),
    ]
